### ISSUE TITLE
When does it connect to the internet and how much traffic does it generate.

### ISSUE THREAD

**Issue by heronils** [atom/metrics#107]
Could you add these infos to the package description?

Specifically, i would like to know if the the package starts when i am in the middle of coding, or if it does its work when the editor starts or closes (preferred). I have no graphics card and a cooler which will notify me when something happens and when i am coding i prefer if nothing happens unless i explicitely request it, i hope you understand, you know, flow

I pay 15 euro for 5 GB internet traffic per month. The info how much traffic the package generates is also of interest to me.

Thanks.

**Comment by annthurium** [comment]
hello @heronils 

We launch a timer when you start Atom, and attempt to send a payload of metrics once every 24 hours.  The size of the payload varies, depending on how much activity you've had during that time period. 

You can disable sending the metrics payload if you'd like -- it's totally understandable to want to save on bandwidth.  Preferences -> Core -> Send Telemetry To The Atom Team.

**Comment by heronils** [comment]
hello @annthurium Thanks a lot for this info.

**Comment by Aerijo** [comment]
@annthurium Would disabling the `metrics` package itself have the same effect?

**Comment by annthurium** [comment]
@Aerijo correct, either way we stop sending telemetry data.
