### ISSUE TITLE
Allow telemetry consent without having it show on my welcome screen everytime I open Atom

### ISSUE THREAD

**Issue by piyush-kgp** [atom/metrics#111]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I don't mind sharing Atom usage statistics to improve the application but hate it asking for my consent everytime I open the application/new window. Currently I dont see any way to do that through settings or config files. (have looked at 1-2 stackoverflow pages too). 
Apologies in advance if there is a way already but I couldn't find any.

### Steps to Reproduce

1. Open Atom app
2. Open settings
3. Check `config.cson` and set `telemetryConsent` variable to "yes". If you cant find it create an item in `core` as `telemetryConsent: "yes"`
4. Open new tab and notice that you have a telemetry consent screen.

**Expected behavior:** [What you expect to happen]
I would not like to see this screen ever whether or not the user decides to share or not share the usage statistics.
**Actual behavior:** Shows that screen

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime you open a new tab
### Versions
1.28.1

### Additional Information
[This answer](https://stackoverflow.com/a/52561841/9563006) solves not showing the telemetry consent page but solves it by not giving consent, hence doesnt solve this issue.

**Comment by 50Wliu** [comment]
Hi @piyush-kgp, could you please fill out the issue template completely?

**Comment by rsese** [comment]
Thanks for filling out the template details :+1:

> * Check `config.cson` and set `telemetryConsent` variable to "yes". If you cant find it create an item in `core` as `telemetryConsent: "yes"`

Looks like the value that's set if you click "Yes, I want to help improve Atom` is `limited` rather than `yes` - if you manually set it to `limited`, does that prevent the consent page from showing?  That prevents the consent page from showing for me.

**Comment by rsese** [comment]
Oh also:

> 1.28.1

The current stable release version of Atom is 1.36.1 so I'd suggest updating as well.

**Comment by piyush-kgp** [comment]
Yes. "limited" does solve the option.
Thank you so much.

**Comment by piyush-kgp** [comment]
> Looks like the value that's set if you click "Yes, I want to help improve Atom`is`limited`rather than`yes`- if you manually set it to`limited`, does that prevent the consent page from showing? That prevents the consent page from showing for me.

Yes. "limited" option does solve the issue.
Thank you so much.
