### ISSUE TITLE
Should I publish my userId?

### ISSUE THREAD

**Issue by hurrymaplelad** [atom/metrics#18]
I noticed `metrics.userId` is stored in my config.cson.  I'd like to commit my config.cson to my [dotfiles](https://github.com/hurrymaplelad/dotfiles).  Should I scrub my `userId` out first?

Related to [execption-reporting#7](https://github.com/atom/exception-reporting/issues/7)

**Comment by robru** [comment]
I find it suspicious that the id is missing from @kevinsawicki 's dotfiles:

https://github.com/kevinsawicki/dotfiles/blob/master/.atom/config.cson

Would be nice if atom stored this somewhere else, it's a hassle to purge it from my config every time I want to commit my changes.

**Comment by thomasjo** [comment]
@robru Why is it suspicious? If you disable the `metrics` package and remove the id, it will stay gone.

**Comment by robru** [comment]
Ah, sorry, I've got my packages confused. `exception-reporting` and `atom-beautify` both also put big hash ids in there. I'll be uninstalling those right quick then...

**Comment by chris-martin** [comment]
I just started using Atom ten minute ago, and found this issue immediately because the first thing I want to do when using a new program is version control its config files. Disabling `exception-reporting` is an irksome fix to have to make after reading a homepage so proudly touting "right out of the box" functionality. Is there an issue to move this data out of the config file?

**Comment by 2E0PGS** [comment]
Thanks guys I remove metrics and exception-reporting then removed the userid. now I got that config in my dotfiles :D cheers.

**Comment by drewcassidy** [comment]
I agree that the user ID should be stored somewhere else, if its the SHA1 of the mac address its intended to be unique per-machine, which kinda defeats the point of sharing your dotfiles with other users and your own other computers

**Comment by damieng** [comment]
The 'userID' is a randomly generated uuid created when the metrics package first activated.  It has not been derived from the mac address for a couple of years.
