### ISSUE TITLE
Reconsider changing how the unique ID is being calculated

### ISSUE THREAD

**Issue by jite** [atom/metrics#23]
You say: "A unique identifier that is generated by computing the SHA-1 of the machine's MAC address."

Now this might not be as important here as in other more sensitive areas, but that is really the wrong way to go, IMO. It is possible to generate hashes for all possible mac addresses and in theory connect/link data to people. It's a pretty long shot but it can be done without too much hassle. Adding some longer random string into each hash would make it as good as useless as identifier but still provide your uniqueness.

**Comment by blobgo** [comment]
What about SHA-265?

**Comment by 50Wliu** [comment]
> Otherwise, they'd just use a cached version 4 UUID and call it a day.

This is now the case - see #54.
