### ISSUE TITLE
Issues when GA cannot be reached

### ISSUE THREAD

**Issue by benogle** [atom/metrics#34]
https://github.com/atom/atom/issues/2394#issuecomment-63200872 via @Spencevail

> My console keeps popping up because it can't reach google analytics. I use Little Snitch and so I blocked google analytics. I would prefer it if my activities and usage were not analyzed. So every few minutes my console is popping up.

**Comment by n1trux** [comment]
This could be solved by using Piwik as proposed in #63.

**Comment by damieng** [comment]
You can disable the metrics plug-in or wait for the forthcoming opt-out.
