### ISSUE TITLE
Cross-Platform shortcuts

### ISSUE THREAD

**Issue by TheJaredWilcurt** [atom/metrics#36]
Your application is crossplatform, your shortcuts should be too.

The readme just says (cmd-,) it should also say (ctrl+,)

* * *

> If you do not want this information reported, disable this package from the
_Metrics_ section of the Settings view (Mac: `cmd-,`) (Win: `ctrl+,`).

* * *

I mean, I know Windows is a minority and only makes up [91.45%](http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0) of the market, but maybe we should treat it like it's on the same level as OSX anyways?

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/metrics/pull/44
