### ISSUE TITLE
Why you don't use Piwik instead of Google Analytics?

### ISSUE THREAD

**Issue by haripetrov** [atom/metrics#43]
I am just curious why you don't use the open source product for web analytics [Piwik](https://github.com/piwik/piwik) instead of Google Analytics?
I am aware that Google Analytics has more functions but you can deploy Piwik in your private environment and in that way you will be sure that the gathered data stays in Github's boundaries.

**Comment by tuxayo** [comment]
+1

**Comment by t128** [comment]
+1

**Comment by dscso** [comment]
+1

**Comment by gnanakeethan** [comment]
+1

**Comment by blobgo** [comment]
:+1:

Indeed I also do not understand how such proprietary code find it's way into an open source project. That's really, really bad.

At least when https://github.com/piwik/piwik/issues/6095 is finished you should switch.

**Comment by Burrito-Bazooka** [comment]
Anyone important paying attention to these issue reports? What's the plan, after half a year?

**Comment by lee-dohm** [comment]
We chose to use Google Analytics originally because it was fast and easy to get something up and running. It continues to be an attractive alternative because it doesn't require us setting up and maintaining our own infrastructure. Longer term we plan to migrate to an internal GitHub metrics infrastructure. We don't have an ETA for when that will happen right now though.

I hope that helps!

**Comment by tuxayo** [comment]
>  Longer term we plan to migrate to an internal GitHub metrics infrastructure. We don't have an ETA for when that will happen right now though.

Thanks, when should we start requesting news about this if we don't hear any follow up?
(I feel like my sentence is poorly worded, can someone tell me a good way to ask this?)

**Comment by n1trux** [comment]
@lee-dohm:
>It continues to be an attractive alternative because it doesn't require us setting up and maintaining our own infrastructure.

Piwik has an auto updater and can be set up and maintained in a few minutes. Your argument is invalid, as far as I am concerned.

**Comment by lee-dohm** [comment]
Answered on the other Issue you opened, @n1trux.
