### ISSUE TITLE
Deprecation Tracking Causing Significant Slowdown

### ISSUE THREAD

**Issue by hughsk** [atom/metrics#47]
I noticed a sudden slowdown in Atom just over the last couple of hours. In that time I've installed (and uninstalled) some autocomplete plugins and Atom appears to have updated from 0.198.0 to 0.199.0. It's now blocking for over 500ms whenever I try to type in the editor, but otherwise operates normally (including typing outside of the editor view):

![screenshot_2015-05-16_1 35 54 pm](https://cloud.githubusercontent.com/assets/569817/7664554/aa07e0b0-fbd0-11e4-878b-4f4e029ae4ae.png)

I then saw that there were over 20,000 errors in my console, which appear to be failed requests to Google Analytics coming from the metric package, reporting deprecated API usage from `npm-install`, `atom-alignment`, `hex`, `command-logger`, `css-colour-underline` and possibly more.

![screenshot_2015-05-16_1 32 25 pm](https://cloud.githubusercontent.com/assets/569817/7664553/a9dc6a66-fbd0-11e4-9152-46edcb1a4a1f.png)

Running on OSX 10.9.2, with `process.versions` being:

``` js
{
  "http_parser": "2.3.0",
  "node": "1.5.1",
  "v8": "4.1.0.21",
  "uv": "1.4.2",
  "zlib": "1.2.8",
  "ares": "1.10.0-DEV",
  "modules": "43",
  "openssl": "1.0.1k",
  "atom-shell": "0.22.3",
  "chrome": "41.0.2272.76"
}
```

I haven't dug any deeper into the problem so far – I seem to have fixed it by disabling the metrics package but just thought a heads up would be appreciated! Thanks :)

**Comment by thedaniel** [comment]
cc @benogle

**Comment by benogle** [comment]
Thanks a bunch for the nice detailed report + profile.
