### ISSUE TITLE
Please publish the data collected with this or make it accessible to researchers

### ISSUE THREAD

**Issue by COLABORATI** [atom/metrics#56]
Please publish the data collected with the metrics package or at least make it available to researchers. 
Should be no problem publishing it, when everything is anonymized, right?

**Comment by burodepeper** [comment]
:+1:

**Comment by logTom** [comment]
:+1: for public metric data.

**Comment by lee-dohm** [comment]
Thanks for the feedback. We'll take a look at what we can release as we can. Thanks again!

**Comment by slang800** [comment]
This should be reopened until it is released

**Comment by MartinMuzatko** [comment]
I would also love to have insights on collected data

**Comment by damieng** [comment]
I personally suspect this would not be possible as no such use of the information was disclosed in policies before/during data collection.

**Comment by slang800** [comment]
@damieng - what policies does Atom have on data collection? The readme of this repo that's linked in the welcome guide just describes _how_ data is collected... I don't see anything that says the data collected will be only given to people within the GitHub/Atom org.

**Comment by damieng** [comment]
https://help.github.com/articles/github-privacy-statement/
