### ISSUE TITLE
What does 'The name of each item opened in a pane such as...' mean?

### ISSUE THREAD

**Issue by kihonkai** [atom/metrics#57]
Hi,  I'm new to Atom having only installed it this morning and played around with it for a bit.  So far I'm liking it a lot.  I wasn't too happy to find it had tracking enabled by default but I won't get into that now.

I saw this item in the collected data:

> The name of each item opened in a pane such as EditorView, SettingsView, and MarkdownPreviewView

Which almost sounds like it would collect filenames.  I didn't think that would be likely and I found issue #16 which talked about the tracking and had this comment:

> No data about filenames or file contents is sent.

That's good to here but I'd be interested if anyone can easily explain what names that original point is referring to.  Any help would be appreciated.

I'm a developer and I know that all the code for this is available.  Once I've started learning more about Atom and the packages I should be able to answer this myself.  I've got one problems if someone wants to close this issue until I can do that.

**Comment by kihonkai** [comment]
Sorry, it seems even after searching I still managed to miss the answer.  I found issue #25 'I believe that metrics should be off by default.' which has this response from @kevinsawicki 

> Google analytics is sent the class name of the pane item opened but not the content inside it. So it reports that you opened an EditorView instance, not that you opened package.json or package.json with content {"foo": "bar"}.

I think it would be good to see that type of information either in the Metrics README.md or in a separate file linked from the README.md so it's clear what information is collected and some examples.

**Comment by thomasjo** [comment]
I believe I've addressed this in #58.
