### ISSUE TITLE
track package usage

### ISSUE THREAD

**Issue by mark-hahn** [atom/metrics#60]
If you were to capture actual usage of packages, i.e. hours per day for each package, it would provide several big benefits. It could be presented in the atom.io package listings. The ratio of downloads to usage would be particulary useful since it would give a good measure of package acceptance. One sort option could be based on usage.

- It would help users pick packages to try. Help find out which ones have happy users.
- It would help package developers like me to find out which packages to focus on. If my package had a bad ratio of downloads to usage I would know to improve it or drop it.

I don't see how this makes privacy any worse.

**Comment by n1trux** [comment]
This could be solved [by using Piwik](https://developer.piwik.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page) as proposed in #63:

>It is possible to configure Piwik so that it accurately measures the time spent on the last page of a visit. [...]
>Piwik will then send requests to count the actual time spent on the page, when the user is actively viewing the page (ie. when the tab is active and in focus). These heartbeat requests will not track additional actions or pageviews.

**Comment by damieng** [comment]
GA is capable of reporting this we don't need a different system.

What however constitutes 'actual usage'?  Packages are activated at start-up but that doesn't mean they are actually being used as such...

**Comment by damieng** [comment]
Unsure of actual requirements or what 'usage' means here especially in terms of hours.  Please re-open if you have clarification.
