### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by alex-gvozden** [atom/metrics#62]
Atom is crashing on MacOSX 10.11.2
to reproduce,

open one Atom window, open another Atom window

close one windows with red X

Atom has crashed, and died, closing everything

**Comment by lee-dohm** [comment]
I suspect that this is a duplicate of https://github.com/atom/atom/issues/9584. This is fixed in the v1.4.x betas.

If I am incorrect, please post a new issue on the https://github.com/atom/atom repository. This repository for the metrics package.
