### ISSUE TITLE
replace Google Analytics with Piwik

### ISSUE THREAD

**Issue by n1trux** [atom/metrics#63]
As [extensively discussed on the official forums](https://discuss.atom.io/t/collecting-metrics-in-atom-core/14178/34) as well as in #43 and #52, I'd like to propose to switch from Google Analytics to [Piwik](http://piwik.org/) to respect the privacy of Atom.io users.

**Comment by lee-dohm** [comment]
As explained in the Issue you linked to, we plan to continue using Google Analytics until we migrate to an  internal GitHub metrics infrastructure. The migration to the internal GitHub metrics infrastructure will achieve the same goal as your proposed migration to Piwik and will require the same commitment of resources.

The resources that we have to spend answering questions that have already been answered cannot then be devoted to things like migrating to any other metrics infrastructure.
