### ISSUE TITLE
should not be opt-in by default 

### ISSUE THREAD

**Issue by vince06fr** [atom/metrics#64]
I understand the need to collect information for help but privacy is more important.
I am using atom 2 month before learning that informations was send to google!!!!

Maybe you can add a dialog when the user launch atom for the first place and ask if he is ok to use metrics for helping atom development.

**Comment by 50Wliu** [comment]
On the Welcome screen when you first start Atom, Atom notifies you that it collects metrics.  Please see #52 for the tracking issue to making metrics opt-in by default.
