### ISSUE TITLE
What does it mean for the following to be sent to google?

### ISSUE THREAD

**Issue by bsouthwood** [atom/metrics#65]
"Exception messages (without paths)" - If I'm using a package, like Juno for Julia, and I get an exception message from a syntax error or something, does this get sent to google?

"Commands run (save core commands)" - What is the definition of a command? Anything I enter into a console?

**Comment by 50Wliu** [comment]
While I do not have access to the Metrics data, I can guess at what each bullet point means:
* Exception messages are most likely core Atom errors (the type that spawn the red popup in the upper-right corner).  For example, `Uncaught TypeError: Cannot read property 'substr' of null`.  I don't use Juno so I can't tell you if those errors would be included.  But if all Juno does is compile Julia code, then no, syntax errors from your Julia code shouldn't be sent.
* Pretty much everything you do in Atom (other than typing) is bound to a _command_.  For example, saving is bound to `core:save`, indenting is `editor:indent`, confirming a textbox is `core:confirm`, etc.  Packages use commands too, like `settings-view:open`.  If one of your packages includes a console, anything you type in that doesn't count as commands, but toggling the console may produce a command.

Does that answer your questions?

**Comment by lee-dohm** [comment]
Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by bsouthwood** [comment]
Thanks. That answers my question, 

I'll message the Atom board in the future.
