### ISSUE TITLE
Atom 1.12.2 tries to re-enable metrics

### ISSUE THREAD

**Issue by posguy99** [atom/metrics#74]
What do you guys not understand about "no"?

**Comment by damieng** [comment]
Can you provide more specific information such as repro steps?  It should definitely not be trying to re-enable them.

**Comment by lee-dohm** [comment]
I was unable to reproduce this. Here's what I did:

1. Ensured that the `core.telemetryConsent` setting was set to `no`
1. Installed Atom v1.12.1
1. Launched Atom v1.12.1
1. Waited for Atom v1.12.2 to download
1. Selected Restart and Install Update
1. Waited for Atom v1.12.2 to launch

Expected and Actual: Both in Settings View and in the `~/.atom/config.cson` the `core.telemetryConsent` value was still set to `no`

**Comment by posguy99** [comment]
So it shouldn't re-display the tab labeled "Telemetry Consent" when the metrics package has already been disabled?  It did.  I went from 1.10.2 to 1.12.2.

**Comment by damieng** [comment]
@lee-dohm is there any scenario where a disabled package might re-enable?

@posguy99 There isn't anything in Atom/metrics that would specifically re-enable this package.  The only way you normally see Telemetry Consent page more than once is if you close the tab without making any choice or if you go into settings and set it back to 'Undecided'.

**Comment by damieng** [comment]
Mystery solved!

The telemetry consent screen itself is displayed by the welcome package and it doesn't check to see if telemetry is disabled. (It should).

Just set this option to no and you shouldn't see it again.  I'll see if we can make the welcome package not display if metrics package is disabled.

**Comment by posguy99** [comment]
I disabled metrics when I first installed Atom way back when, before v1.0.  I don't remember being asked, Atom enabled it by default and you had to read release notes to know it was there and to disable it.

Let me ask a question... when did this idiotic "Telemetry Consent" thing get added and why doesn't it look at the current state of the metrics package?  Maybe that's what it is, did it get added between the last time I launched Atom (v1.10.2) and this time (1.12.2)?

When will people learn that the correct default for all these things is "disabled", and you let the user enable them if they want to participate?  "Telemetry Consent" had the Enable button (whatever it's labeled, it's an "enable button) selected.  Of course I chose disabled.

I get it, it's "works as designed", it's just bad design.

**Comment by lee-dohm** [comment]
The Telemetry Consent tab is displayed by the welcome package (which governs our first-time launch experience), not the metrics package. The Telemetry Consent tab will be displayed any time the welcome package is enabled and the `core.telemetryConsent` configuration value is neither `no` or `limited`. Disabling the metrics package will have no effect on whether or not this tab is displayed.

**Comment by damieng** [comment]
The reason it still asks is that just disabling the metrics package won't also disable exception-reporting.  The new telemetry consent screen can effectively disable both.

**Comment by posguy99** [comment]
Final comment... certainly wasn't a first-time launch, so your welcome package is broken as well.  Plus I have show on startup set to false.  Disabled that one too now.

**Comment by damieng** [comment]
It was a separate setting in welcome package so that the majority of users who haven't disabled metrics have a chance to opt-out or opt-in.

**Comment by posguy99** [comment]
I just tested, if you don't disable the exception-reporting package, it will keep recreating the encoded MAC of the machine.

**Comment by damieng** [comment]
Are you referring to 'exception-reporting.userId' ?  If so that is a random generated GUID not the MAC address.

**Comment by posguy99** [comment]
It was a direct indicator that even if you explicitly disabled telemetry, that exception reporting was left enabled. 

-- 
 Marc Wilson
