### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by dylan-k** [atom/metrics#76]
Argument to `path.dirname` must be a string
```
Object.dirname (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
Function.viewNameForPaneItem (/Users/dylankinnett/.atom/packages/metrics/lib/reporter.coffee:96:16)
Function.sendPaneItem (/Users/dylankinnett/.atom/packages/metrics/lib/reporter.coffee:133:18)
<unknown> (/Users/dylankinnett/.atom/packages/metrics/lib/metrics.coffee:114:27)
Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
```

**Comment by 50Wliu** [comment]
@dylan-k please uninstall metrics.  It isn't meant to be installed manually.

/cc @damieng: this error seems to be referring to https://github.com/atom/metrics/blob/df0c45891786394b51d5f9e7833e84a71d1c605c/lib/reporter.coffee#L65.  Looks like L63 needs to be updated.

**Comment by damieng** [comment]
path.dirName is not deprecated according to the latest node docs https://nodejs.org/api/path.html#path_path_dirname_path

**Comment by 50Wliu** [comment]
It's not that it's deprecated, we just have to make sure we pass string arguments to it.

**Comment by ev1stensberg** [comment]
Any update on this?

**Comment by as-cii** [comment]
Thanks everyone for the reports! The fix for this issue will go out on the next stable and beta releases, which should be published later this week.
