### ISSUE TITLE
Depreciation warning in metrics

### ISSUE THREAD

**Issue by afzalSH** [atom/metrics#82]
I am new to Atom and received the following message; "You have the core package "metrics" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation."
```
<unknown> (/usr/share/atom/resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/usr/share/atom/resources/app.asar/src/package-manager.js:514:32)
```

**Comment by rsese** [comment]
See the error message for details on how to resolve this problem:

> You have the core package "metrics" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

In particular, see this section of the https://github.com/atom/dalek README for step-by-step instructions:

https://github.com/atom/dalek#i-got-a-warning-what-do-i-do

Let me know if you have any trouble with the process.
